language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=android-20
    - ANDROID_ABI=armeabi-v7a
before-install:
  - echo "y" | $ANDROID_HOME/tools/android update sdk --filter tools,platform-tools,build-tools-20.0.0,android-20 --no-ui --force
  
android:
  components:
    - build-tools-20.0.0
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5 # new license!
    - '.*intel.+'
    
script: ./gradlew assembleDebug
