#!/bin/bash

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )" " ) )"

cp $PROJECT_ROOT/app/AndroidManifest.example $PROJECT_ROOT/app/src/debug/AndroidManifest.xml
cp $PROJECT_ROOT/app/AndroidManifest.example $PROJECT_ROOT/app/src/release/AndroidManifest.xml

cp $PROJECT_ROOT/app/secrets.example $PROJECT_ROOT/app/src/debug/res/values/strings.xml
cp $PROJECT_ROOT/app/secrets.example $PROJECT_ROOT/app/src/release/res/values/strings.xml

cp $PROJECT_ROOT/server/appengine-web.example $PROJECT_ROOT/server/src/webapp/WEB-INF/appengine-web.xml
